name: test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  equatable: 1.2.5

dev_dependencies:
  pedantic: ^1.9.0
